### PR TITLE
Fuzzy search

### PR DESCRIPTION
**Pull request by JindrichPilar**
If fuzzy search is enabled, completion is combined from multiple searches in this order:

  - Exact match (as is now)
  - If search query contains `/` then it matches `.*/.*`
  - If search query contains ` ` then it matches `.*`

### CODE REVIEW

**Comment by 1995eaton** [comment]
This seems to not be working for me.

**Comment by JindrichPilar** [comment]
When you do all the things listed in "contributing" section, then:
``:history git chro vim fuzzy`` will suggest me this PR, issue and branch in my repo. Which is all correct. Also configuration is working.

I am not completely familiar with codebase, so probably I have misused ``Settings``.
Problem seems to be sometimes ``searchArray`` doesn't have access to ``Settings`` variable (it is undefined). Because it doesn't exist in context of the caller. What is the correct way to access configuration?

**Comment by JindrichPilar** [comment]
I have pushed a fix to fallback to classic search if ``Settings`` is not defined.

**Comment by 1995eaton** [comment]
The reason it wasn't working was because `Settings` should be `settings` (`Settings` can only be accessed via the background scripts). Anyways, I've already pushed 099c922, which implements this feature without using regex to search for items. I ended up splitting terms into arrays by delimiters and searching by comparing terms in the arrays (which I believe is what Chrome does in the omnibox). Thanks for the PR though!

**Pull request closed without merging**
