### PR TITLE
Make scroll still work on pages using scroll div like "Atlassian Confluence"

### PR DESCRIPTION
**Pull request by hiberabyss**
Still need to click on the content you want to scroll.

### CODE REVIEW

**Comment by 1995eaton** [comment]
Could you give me a specific URL where the scrolling doesn't work? I think this may no longer be an issue, but I'm not entirely sure.

**Comment by hiberabyss** [comment]
Hi @1995eaton 

For this [page](http://fishshell.com/docs/current/index.html), the scrolling still doesn't work with the cVim in chrome webstrore.

**Comment by 1995eaton** [comment]
It's working for me. You have to click on the region you want to scroll (similar to what you have to do when you scroll with Chrome's native up/down keys).

**Comment by hiberabyss** [comment]
I clicked on the region, but the scrolling with j/k still does not work.
cvim version:  1.2.85
chrome version:  51.0.2704.106 (64-bit).

**Pull request closed without merging**
