### PR TITLE
Fixed scrollTop not working on body element. (in SrollTopLeftInterop mode)

### PR DESCRIPTION
**Pull request by gogu**
`document.body.scrollTop` always 0 on Chrome 48.0.2564.116.

### CODE REVIEW

**Comment by 1995eaton** [comment]
Strange... for me, `document.documentElement.scrollTop` is always zero for me (using linux). This PR breaks scrolling and link hints for me. What operating system are you using?

**Comment by rguanghui** [comment]
seems a problem from chrome, how to use `document.body.scrollTop || document.documentElement.scrollTop` ?

**Comment by gogu** [comment]
I'm using OSX 10.11.3.
I found out my problem was happening while `#enable-experimental-web-platform-features` is opening.
`ScrollTopLeftInterop` feature made html as the scroll element.

@1995eaton @rguanghui 
How about use `document.scrollingElement` (supported by Chromium 44 or later) ?

https://bugs.chromium.org/p/chromium/issues/detail?id=452478
https://dev.opera.com/articles/fixing-the-scrolltop-bug/

**Comment by 1995eaton** [comment]
@gogu Just merged the `scrollingElement` fix, and it works. Thanks for the PR!

**Pull request merged**
