### PR TITLE
Match in any position when search history or bookmarks

### PR DESCRIPTION
**Pull request by hiberabyss**
Currently, search history can only match from the begin of string (e.g. `gtest` can't match `GoogleTest(gtest)`. With this PR, once the url or title item contains search item, it will match (e.g. `template` will match `CppTemplateTutorial`).

### CODE REVIEW

**Comment by Ape** [comment]
I tried this. The change doesn't affect my use often, but when it does it just seems to add more irrelevant results (this is subjective and depends on search habits of course). Could you make it optional at least?

**Comment by hiberabyss** [comment]
Hi, @Ape 
I have add option `matchfrombegin` in new commits.

PS: What's the difference between `Settings` and `settings` ? It makes me confused. Thanks.

**Comment by Ape** [comment]
I think you can just use ```settings.matchfrombegin``` and not check for ```undefined```.

**Comment by hiberabyss** [comment]
Use settings only makes search in `:history` doesn't work.

**Comment by 1995eaton** [comment]
I agree with @Ape. I think the command bar yields more relevant results when it only matches the beginning of words. Implementing a more advanced searching algorithm would be preferable For example, `words` would match `TwoWords`, but not `twowords`.

**Pull request closed without merging**
